services:
  - type: web
    name: stock-analysis
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 app.py
    envVars:
      - key: PORT
        value: 5001
      - key: SECRET_KEY
        generateValue: true
        sync: false
    plan: free